/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central account entity
     * @type {string}
     * @memberof Account
     */
    'id'?: string;
    /**
     * (v1.0) The number property for the Dynamics 365 Business Central account entity
     * @type {string}
     * @memberof Account
     */
    'number'?: string | null;
    /**
     * (v1.0) The displayName property for the Dynamics 365 Business Central account entity
     * @type {string}
     * @memberof Account
     */
    'displayName'?: string | null;
    /**
     * (v1.0) The category property for the Dynamics 365 Business Central account entity
     * @type {string}
     * @memberof Account
     */
    'category'?: string | null;
    /**
     * (v1.0) The subCategory property for the Dynamics 365 Business Central account entity
     * @type {string}
     * @memberof Account
     */
    'subCategory'?: string | null;
    /**
     * (v1.0) The blocked property for the Dynamics 365 Business Central account entity
     * @type {boolean}
     * @memberof Account
     */
    'blocked'?: boolean | null;
    /**
     * (v1.0) The lastModifiedDateTime property for the Dynamics 365 Business Central account entity
     * @type {string}
     * @memberof Account
     */
    'lastModifiedDateTime'?: string | null;
}

