/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central currency entity
     * @type {string}
     * @memberof Currency
     */
    'id'?: string;
    /**
     * (v1.0) The code property for the Dynamics 365 Business Central currency entity
     * @type {string}
     * @memberof Currency
     */
    'code'?: string;
    /**
     * (v1.0) The displayName property for the Dynamics 365 Business Central currency entity
     * @type {string}
     * @memberof Currency
     */
    'displayName'?: string | null;
    /**
     * (v1.0) The symbol property for the Dynamics 365 Business Central currency entity
     * @type {string}
     * @memberof Currency
     */
    'symbol'?: string | null;
    /**
     * (v1.0) The amountDecimalPlaces property for the Dynamics 365 Business Central currency entity
     * @type {string}
     * @memberof Currency
     */
    'amountDecimalPlaces'?: string | null;
    /**
     * (v1.0) The amountRoundingPrecision property for the Dynamics 365 Business Central currency entity
     * @type {number}
     * @memberof Currency
     */
    'amountRoundingPrecision'?: number | null;
    /**
     * (v1.0) The lastModifiedDateTime property for the Dynamics 365 Business Central currency entity
     * @type {string}
     * @memberof Currency
     */
    'lastModifiedDateTime'?: string | null;
}

