/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerFinancialDetail
 */
export interface CustomerFinancialDetail {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central customerFinancialDetail entity
     * @type {string}
     * @memberof CustomerFinancialDetail
     */
    'id'?: string;
    /**
     * (v1.0) The number property for the Dynamics 365 Business Central customerFinancialDetail entity
     * @type {string}
     * @memberof CustomerFinancialDetail
     */
    'number'?: string | null;
    /**
     * (v1.0) The balance property for the Dynamics 365 Business Central customerFinancialDetail entity
     * @type {number}
     * @memberof CustomerFinancialDetail
     */
    'balance'?: number | null;
    /**
     * (v1.0) The totalSalesExcludingTax property for the Dynamics 365 Business Central customerFinancialDetail entity
     * @type {number}
     * @memberof CustomerFinancialDetail
     */
    'totalSalesExcludingTax'?: number | null;
    /**
     * (v1.0) The overdueAmount property for the Dynamics 365 Business Central customerFinancialDetail entity
     * @type {number}
     * @memberof CustomerFinancialDetail
     */
    'overdueAmount'?: number | null;
}

