/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Account } from './account';
// May contain unused imports in some cases
// @ts-ignore
import type { Dimension } from './dimension';
// May contain unused imports in some cases
// @ts-ignore
import type { DimensionValue } from './dimension-value';

/**
 * 
 * @export
 * @interface DefaultDimensions
 */
export interface DefaultDimensions {
    /**
     * (v1.0) The parentId property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof DefaultDimensions
     */
    'parentId'?: string;
    /**
     * (v1.0) The dimensionId property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof DefaultDimensions
     */
    'dimensionId'?: string;
    /**
     * (v1.0) The dimensionCode property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof DefaultDimensions
     */
    'dimensionCode'?: string | null;
    /**
     * (v1.0) The dimensionValueId property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof DefaultDimensions
     */
    'dimensionValueId'?: string | null;
    /**
     * (v1.0) The dimensionValueCode property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof DefaultDimensions
     */
    'dimensionValueCode'?: string | null;
    /**
     * (v1.0) The postingValidation property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof DefaultDimensions
     */
    'postingValidation'?: string | null;
    /**
     * 
     * @type {Account}
     * @memberof DefaultDimensions
     */
    'account'?: Account;
    /**
     * 
     * @type {Dimension}
     * @memberof DefaultDimensions
     */
    'dimension'?: Dimension;
    /**
     * 
     * @type {DimensionValue}
     * @memberof DefaultDimensions
     */
    'dimensionValue'?: DimensionValue;
}

