/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GeneralLedgerEntry } from './general-ledger-entry';

/**
 * 
 * @export
 * @interface GeneralLedgerEntryAttachments
 */
export interface GeneralLedgerEntryAttachments {
    /**
     * (v1.0) The generalLedgerEntryNumber property for the Dynamics 365 Business Central generalLedgerEntryAttachments entity
     * @type {number}
     * @memberof GeneralLedgerEntryAttachments
     */
    'generalLedgerEntryNumber'?: number;
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central generalLedgerEntryAttachments entity
     * @type {string}
     * @memberof GeneralLedgerEntryAttachments
     */
    'id'?: string;
    /**
     * (v1.0) The fileName property for the Dynamics 365 Business Central generalLedgerEntryAttachments entity
     * @type {string}
     * @memberof GeneralLedgerEntryAttachments
     */
    'fileName'?: string | null;
    /**
     * (v1.0) The byteSize property for the Dynamics 365 Business Central generalLedgerEntryAttachments entity
     * @type {number}
     * @memberof GeneralLedgerEntryAttachments
     */
    'byteSize'?: number | null;
    /**
     * (v1.0) The content property for the Dynamics 365 Business Central generalLedgerEntryAttachments entity
     * @type {File}
     * @memberof GeneralLedgerEntryAttachments
     */
    'content'?: File | null;
    /**
     * (v1.0) The createdDateTime property for the Dynamics 365 Business Central generalLedgerEntryAttachments entity
     * @type {string}
     * @memberof GeneralLedgerEntryAttachments
     */
    'createdDateTime'?: string | null;
    /**
     * 
     * @type {GeneralLedgerEntry}
     * @memberof GeneralLedgerEntryAttachments
     */
    'generalLedgerEntry'?: GeneralLedgerEntry;
}

