/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IncomeStatement
 */
export interface IncomeStatement {
    /**
     * (v1.0) The lineNumber property for the Dynamics 365 Business Central incomeStatement entity
     * @type {number}
     * @memberof IncomeStatement
     */
    'lineNumber'?: number;
    /**
     * (v1.0) The display property for the Dynamics 365 Business Central incomeStatement entity
     * @type {string}
     * @memberof IncomeStatement
     */
    'display'?: string | null;
    /**
     * (v1.0) The netChange property for the Dynamics 365 Business Central incomeStatement entity
     * @type {number}
     * @memberof IncomeStatement
     */
    'netChange'?: number | null;
    /**
     * (v1.0) The lineType property for the Dynamics 365 Business Central incomeStatement entity
     * @type {string}
     * @memberof IncomeStatement
     */
    'lineType'?: string | null;
    /**
     * (v1.0) The indentation property for the Dynamics 365 Business Central incomeStatement entity
     * @type {number}
     * @memberof IncomeStatement
     */
    'indentation'?: number | null;
    /**
     * (v1.0) The dateFilter property for the Dynamics 365 Business Central incomeStatement entity
     * @type {string}
     * @memberof IncomeStatement
     */
    'dateFilter'?: string | null;
}

