/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DefaultDimensions } from './default-dimensions';

/**
 * 
 * @export
 * @interface ListDefaultDimensionsForItem200Response
 */
export interface ListDefaultDimensionsForItem200Response {
    /**
     * 
     * @type {Array<DefaultDimensions>}
     * @memberof ListDefaultDimensionsForItem200Response
     */
    'value'?: Array<DefaultDimensions>;
}

