/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchPictureForItemRequest
 */
export interface PatchPictureForItemRequest {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central picture entity
     * @type {string}
     * @memberof PatchPictureForItemRequest
     */
    'id'?: string;
    /**
     * (v1.0) The width property for the Dynamics 365 Business Central picture entity
     * @type {number}
     * @memberof PatchPictureForItemRequest
     */
    'width'?: number | null;
    /**
     * (v1.0) The height property for the Dynamics 365 Business Central picture entity
     * @type {number}
     * @memberof PatchPictureForItemRequest
     */
    'height'?: number | null;
    /**
     * (v1.0) The contentType property for the Dynamics 365 Business Central picture entity
     * @type {string}
     * @memberof PatchPictureForItemRequest
     */
    'contentType'?: string | null;
    /**
     * (v1.0) The content property for the Dynamics 365 Business Central picture entity
     * @type {File}
     * @memberof PatchPictureForItemRequest
     */
    'content'?: File | null;
}

