/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentTerm
 */
export interface PaymentTerm {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central paymentTerm entity
     * @type {string}
     * @memberof PaymentTerm
     */
    'id'?: string;
    /**
     * (v1.0) The code property for the Dynamics 365 Business Central paymentTerm entity
     * @type {string}
     * @memberof PaymentTerm
     */
    'code'?: string;
    /**
     * (v1.0) The displayName property for the Dynamics 365 Business Central paymentTerm entity
     * @type {string}
     * @memberof PaymentTerm
     */
    'displayName'?: string | null;
    /**
     * (v1.0) The dueDateCalculation property for the Dynamics 365 Business Central paymentTerm entity
     * @type {string}
     * @memberof PaymentTerm
     */
    'dueDateCalculation'?: string | null;
    /**
     * (v1.0) The discountDateCalculation property for the Dynamics 365 Business Central paymentTerm entity
     * @type {string}
     * @memberof PaymentTerm
     */
    'discountDateCalculation'?: string | null;
    /**
     * (v1.0) The discountPercent property for the Dynamics 365 Business Central paymentTerm entity
     * @type {number}
     * @memberof PaymentTerm
     */
    'discountPercent'?: number | null;
    /**
     * (v1.0) The calculateDiscountOnCreditMemos property for the Dynamics 365 Business Central paymentTerm entity
     * @type {boolean}
     * @memberof PaymentTerm
     */
    'calculateDiscountOnCreditMemos'?: boolean | null;
    /**
     * (v1.0) The lastModifiedDateTime property for the Dynamics 365 Business Central paymentTerm entity
     * @type {string}
     * @memberof PaymentTerm
     */
    'lastModifiedDateTime'?: string | null;
}

