/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Postaladdresstype } from './postaladdresstype';

/**
 * 
 * @export
 * @interface PostEmployeeRequest
 */
export interface PostEmployeeRequest {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'id'?: string;
    /**
     * (v1.0) The number property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'number'?: string | null;
    /**
     * (v1.0) The displayName property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'displayName'?: string | null;
    /**
     * (v1.0) The givenName property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'givenName'?: string | null;
    /**
     * (v1.0) The middleName property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'middleName'?: string | null;
    /**
     * (v1.0) The surname property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'surname'?: string | null;
    /**
     * (v1.0) The jobTitle property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'jobTitle'?: string | null;
    /**
     * 
     * @type {Postaladdresstype}
     * @memberof PostEmployeeRequest
     */
    'address'?: Postaladdresstype;
    /**
     * (v1.0) The phoneNumber property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'phoneNumber'?: string | null;
    /**
     * (v1.0) The mobilePhone property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'mobilePhone'?: string | null;
    /**
     * (v1.0) The email property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'email'?: string | null;
    /**
     * (v1.0) The personalEmail property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'personalEmail'?: string | null;
    /**
     * (v1.0) The employmentDate property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'employmentDate'?: string | null;
    /**
     * (v1.0) The terminationDate property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'terminationDate'?: string | null;
    /**
     * (v1.0) The status property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'status'?: string | null;
    /**
     * (v1.0) The birthDate property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'birthDate'?: string | null;
    /**
     * (v1.0) The statisticsGroupCode property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'statisticsGroupCode'?: string | null;
    /**
     * (v1.0) The lastModifiedDateTime property for the Dynamics 365 Business Central employee entity
     * @type {string}
     * @memberof PostEmployeeRequest
     */
    'lastModifiedDateTime'?: string | null;
}

