/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Unitofmeasuretype } from './unitofmeasuretype';

/**
 * 
 * @export
 * @interface PostItemRequest
 */
export interface PostItemRequest {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'id'?: string;
    /**
     * (v1.0) The number property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'number'?: string | null;
    /**
     * (v1.0) The displayName property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'displayName'?: string | null;
    /**
     * (v1.0) The type property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'type'?: string | null;
    /**
     * (v1.0) The itemCategoryId property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'itemCategoryId'?: string | null;
    /**
     * (v1.0) The itemCategoryCode property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'itemCategoryCode'?: string | null;
    /**
     * (v1.0) The blocked property for the Dynamics 365 Business Central item entity
     * @type {boolean}
     * @memberof PostItemRequest
     */
    'blocked'?: boolean | null;
    /**
     * (v1.0) The baseUnitOfMeasureId property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'baseUnitOfMeasureId'?: string | null;
    /**
     * 
     * @type {Unitofmeasuretype}
     * @memberof PostItemRequest
     */
    'baseUnitOfMeasure'?: Unitofmeasuretype;
    /**
     * (v1.0) The gtin property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'gtin'?: string | null;
    /**
     * (v1.0) The inventory property for the Dynamics 365 Business Central item entity
     * @type {number}
     * @memberof PostItemRequest
     */
    'inventory'?: number | null;
    /**
     * (v1.0) The unitPrice property for the Dynamics 365 Business Central item entity
     * @type {number}
     * @memberof PostItemRequest
     */
    'unitPrice'?: number | null;
    /**
     * (v1.0) The priceIncludesTax property for the Dynamics 365 Business Central item entity
     * @type {boolean}
     * @memberof PostItemRequest
     */
    'priceIncludesTax'?: boolean | null;
    /**
     * (v1.0) The unitCost property for the Dynamics 365 Business Central item entity
     * @type {number}
     * @memberof PostItemRequest
     */
    'unitCost'?: number | null;
    /**
     * (v1.0) The taxGroupId property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'taxGroupId'?: string | null;
    /**
     * (v1.0) The taxGroupCode property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'taxGroupCode'?: string | null;
    /**
     * (v1.0) The lastModifiedDateTime property for the Dynamics 365 Business Central item entity
     * @type {string}
     * @memberof PostItemRequest
     */
    'lastModifiedDateTime'?: string | null;
}

