/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostDefaultDimensionsForItemRequest
 */
export interface PostDefaultDimensionsForItemRequest {
    /**
     * (v1.0) The parentId property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof PostDefaultDimensionsForItemRequest
     */
    'parentId'?: string;
    /**
     * (v1.0) The dimensionId property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof PostDefaultDimensionsForItemRequest
     */
    'dimensionId'?: string;
    /**
     * (v1.0) The dimensionCode property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof PostDefaultDimensionsForItemRequest
     */
    'dimensionCode'?: string | null;
    /**
     * (v1.0) The dimensionValueId property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof PostDefaultDimensionsForItemRequest
     */
    'dimensionValueId'?: string | null;
    /**
     * (v1.0) The dimensionValueCode property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof PostDefaultDimensionsForItemRequest
     */
    'dimensionValueCode'?: string | null;
    /**
     * (v1.0) The postingValidation property for the Dynamics 365 Business Central defaultDimensions entity
     * @type {string}
     * @memberof PostDefaultDimensionsForItemRequest
     */
    'postingValidation'?: string | null;
}

