/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomerFinancialDetail } from './customer-financial-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { DefaultDimensions } from './default-dimensions';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethod } from './payment-method';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentTerm } from './payment-term';
// May contain unused imports in some cases
// @ts-ignore
import type { Picture } from './picture';
// May contain unused imports in some cases
// @ts-ignore
import type { ShipmentMethod } from './shipment-method';

/**
 * 
 * @export
 * @interface Postaladdresstype
 */
export interface Postaladdresstype {
    /**
     * (v1.0) The street property for the Dynamics 365 Business Central postaladdresstype entity
     * @type {string}
     * @memberof Postaladdresstype
     */
    'street'?: string | null;
    /**
     * (v1.0) The city property for the Dynamics 365 Business Central postaladdresstype entity
     * @type {string}
     * @memberof Postaladdresstype
     */
    'city'?: string | null;
    /**
     * (v1.0) The state property for the Dynamics 365 Business Central postaladdresstype entity
     * @type {string}
     * @memberof Postaladdresstype
     */
    'state'?: string | null;
    /**
     * (v1.0) The countryLetterCode property for the Dynamics 365 Business Central postaladdresstype entity
     * @type {string}
     * @memberof Postaladdresstype
     */
    'countryLetterCode'?: string | null;
    /**
     * (v1.0) The postalCode property for the Dynamics 365 Business Central postaladdresstype entity
     * @type {string}
     * @memberof Postaladdresstype
     */
    'postalCode'?: string | null;
    /**
     * 
     * @type {Array<CustomerFinancialDetail>}
     * @memberof Postaladdresstype
     */
    'customerFinancialDetails'?: Array<CustomerFinancialDetail> | null;
    /**
     * 
     * @type {Array<Picture>}
     * @memberof Postaladdresstype
     */
    'picture'?: Array<Picture> | null;
    /**
     * 
     * @type {Array<DefaultDimensions>}
     * @memberof Postaladdresstype
     */
    'defaultDimensions'?: Array<DefaultDimensions> | null;
    /**
     * 
     * @type {Currency}
     * @memberof Postaladdresstype
     */
    'currency'?: Currency;
    /**
     * 
     * @type {PaymentTerm}
     * @memberof Postaladdresstype
     */
    'paymentTerm'?: PaymentTerm;
    /**
     * 
     * @type {ShipmentMethod}
     * @memberof Postaladdresstype
     */
    'shipmentMethod'?: ShipmentMethod;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof Postaladdresstype
     */
    'paymentMethod'?: PaymentMethod;
}

