/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { PdfDocument } from './pdf-document';
// May contain unused imports in some cases
// @ts-ignore
import type { Postaladdresstype } from './postaladdresstype';
// May contain unused imports in some cases
// @ts-ignore
import type { PurchaseInvoiceLine } from './purchase-invoice-line';
// May contain unused imports in some cases
// @ts-ignore
import type { Vendor } from './vendor';

/**
 * 
 * @export
 * @interface PurchaseInvoice
 */
export interface PurchaseInvoice {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'id'?: string;
    /**
     * (v1.0) The number property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'number'?: string | null;
    /**
     * (v1.0) The invoiceDate property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'invoiceDate'?: string | null;
    /**
     * (v1.0) The dueDate property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'dueDate'?: string | null;
    /**
     * (v1.0) The vendorInvoiceNumber property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'vendorInvoiceNumber'?: string | null;
    /**
     * (v1.0) The vendorId property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'vendorId'?: string | null;
    /**
     * (v1.0) The vendorNumber property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'vendorNumber'?: string | null;
    /**
     * (v1.0) The vendorName property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'vendorName'?: string | null;
    /**
     * (v1.0) The payToName property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'payToName'?: string | null;
    /**
     * (v1.0) The payToContact property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'payToContact'?: string | null;
    /**
     * (v1.0) The payToVendorId property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'payToVendorId'?: string | null;
    /**
     * (v1.0) The payToVendorNumber property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'payToVendorNumber'?: string | null;
    /**
     * (v1.0) The shipToName property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'shipToName'?: string | null;
    /**
     * (v1.0) The shipToContact property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'shipToContact'?: string | null;
    /**
     * 
     * @type {Postaladdresstype}
     * @memberof PurchaseInvoice
     */
    'buyFromAddress'?: Postaladdresstype;
    /**
     * 
     * @type {Postaladdresstype}
     * @memberof PurchaseInvoice
     */
    'payToAddress'?: Postaladdresstype;
    /**
     * 
     * @type {Postaladdresstype}
     * @memberof PurchaseInvoice
     */
    'shipToAddress'?: Postaladdresstype;
    /**
     * (v1.0) The currencyId property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'currencyId'?: string | null;
    /**
     * (v1.0) The currencyCode property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'currencyCode'?: string | null;
    /**
     * (v1.0) The pricesIncludeTax property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {boolean}
     * @memberof PurchaseInvoice
     */
    'pricesIncludeTax'?: boolean | null;
    /**
     * (v1.0) The discountAmount property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {number}
     * @memberof PurchaseInvoice
     */
    'discountAmount'?: number | null;
    /**
     * (v1.0) The discountAppliedBeforeTax property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {boolean}
     * @memberof PurchaseInvoice
     */
    'discountAppliedBeforeTax'?: boolean | null;
    /**
     * (v1.0) The totalAmountExcludingTax property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {number}
     * @memberof PurchaseInvoice
     */
    'totalAmountExcludingTax'?: number | null;
    /**
     * (v1.0) The totalTaxAmount property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {number}
     * @memberof PurchaseInvoice
     */
    'totalTaxAmount'?: number | null;
    /**
     * (v1.0) The totalAmountIncludingTax property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {number}
     * @memberof PurchaseInvoice
     */
    'totalAmountIncludingTax'?: number | null;
    /**
     * (v1.0) The status property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'status'?: string | null;
    /**
     * (v1.0) The lastModifiedDateTime property for the Dynamics 365 Business Central purchaseInvoice entity
     * @type {string}
     * @memberof PurchaseInvoice
     */
    'lastModifiedDateTime'?: string | null;
    /**
     * 
     * @type {Array<PurchaseInvoiceLine>}
     * @memberof PurchaseInvoice
     */
    'purchaseInvoiceLines'?: Array<PurchaseInvoiceLine> | null;
    /**
     * 
     * @type {Array<PdfDocument>}
     * @memberof PurchaseInvoice
     */
    'pdfDocument'?: Array<PdfDocument> | null;
    /**
     * 
     * @type {Vendor}
     * @memberof PurchaseInvoice
     */
    'vendor'?: Vendor;
    /**
     * 
     * @type {Currency}
     * @memberof PurchaseInvoice
     */
    'currency'?: Currency;
}

