/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Account } from './account';
// May contain unused imports in some cases
// @ts-ignore
import type { Documentlineobjectdetailstype } from './documentlineobjectdetailstype';
// May contain unused imports in some cases
// @ts-ignore
import type { Item } from './item';
// May contain unused imports in some cases
// @ts-ignore
import type { Unitofmeasuretype } from './unitofmeasuretype';

/**
 * 
 * @export
 * @interface SalesQuoteLine
 */
export interface SalesQuoteLine {
    /**
     * (v1.0) The id property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {string}
     * @memberof SalesQuoteLine
     */
    'id'?: string;
    /**
     * (v1.0) The documentId property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {string}
     * @memberof SalesQuoteLine
     */
    'documentId'?: string | null;
    /**
     * (v1.0) The sequence property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'sequence'?: number | null;
    /**
     * (v1.0) The itemId property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {string}
     * @memberof SalesQuoteLine
     */
    'itemId'?: string | null;
    /**
     * (v1.0) The accountId property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {string}
     * @memberof SalesQuoteLine
     */
    'accountId'?: string | null;
    /**
     * (v1.0) The lineType property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {string}
     * @memberof SalesQuoteLine
     */
    'lineType'?: string | null;
    /**
     * 
     * @type {Documentlineobjectdetailstype}
     * @memberof SalesQuoteLine
     */
    'lineDetails'?: Documentlineobjectdetailstype;
    /**
     * (v1.0) The description property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {string}
     * @memberof SalesQuoteLine
     */
    'description'?: string | null;
    /**
     * (v1.0) The unitOfMeasureId property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {string}
     * @memberof SalesQuoteLine
     */
    'unitOfMeasureId'?: string | null;
    /**
     * 
     * @type {Unitofmeasuretype}
     * @memberof SalesQuoteLine
     */
    'unitOfMeasure'?: Unitofmeasuretype;
    /**
     * (v1.0) The unitPrice property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'unitPrice'?: number | null;
    /**
     * (v1.0) The quantity property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'quantity'?: number | null;
    /**
     * (v1.0) The discountAmount property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'discountAmount'?: number | null;
    /**
     * (v1.0) The discountPercent property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'discountPercent'?: number | null;
    /**
     * (v1.0) The discountAppliedBeforeTax property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {boolean}
     * @memberof SalesQuoteLine
     */
    'discountAppliedBeforeTax'?: boolean | null;
    /**
     * (v1.0) The amountExcludingTax property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'amountExcludingTax'?: number | null;
    /**
     * (v1.0) The taxCode property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {string}
     * @memberof SalesQuoteLine
     */
    'taxCode'?: string | null;
    /**
     * (v1.0) The taxPercent property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'taxPercent'?: number | null;
    /**
     * (v1.0) The totalTaxAmount property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'totalTaxAmount'?: number | null;
    /**
     * (v1.0) The amountIncludingTax property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'amountIncludingTax'?: number | null;
    /**
     * (v1.0) The netAmount property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'netAmount'?: number | null;
    /**
     * (v1.0) The netTaxAmount property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'netTaxAmount'?: number | null;
    /**
     * (v1.0) The netAmountIncludingTax property for the Dynamics 365 Business Central salesQuoteLine entity
     * @type {number}
     * @memberof SalesQuoteLine
     */
    'netAmountIncludingTax'?: number | null;
    /**
     * 
     * @type {Item}
     * @memberof SalesQuoteLine
     */
    'item'?: Item;
    /**
     * 
     * @type {Account}
     * @memberof SalesQuoteLine
     */
    'account'?: Account;
}

