/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BalanceSheet } from '../model';
// @ts-ignore
import type { ListBalanceSheet200Response } from '../model';
/**
 * BalanceSheetApi - axios parameter creator
 * @export
 */
export const BalanceSheetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Retrieve the properties and relationships of an object of type balanceSheet for Dynamics 365 Business Central.
         * @param {string} companyId (v1.0) id for company
         * @param {number} balanceSheetLineNumber (v1.0) lineNumber for balanceSheet
         * @param {Array<GetBalanceSheetSelectEnum>} [$select] (v1.0) Selected properties to be retrieved
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBalanceSheet: async (companyId: string, balanceSheetLineNumber: number, $select?: Array<GetBalanceSheetSelectEnum>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getBalanceSheet', 'companyId', companyId)
            // verify required parameter 'balanceSheetLineNumber' is not null or undefined
            assertParamExists('getBalanceSheet', 'balanceSheetLineNumber', balanceSheetLineNumber)
            const localVarPath = `/companies({company_id})/balanceSheet({balanceSheet_lineNumber})`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)))
                .replace(`{${"balanceSheet_lineNumber"}}`, encodeURIComponent(String(balanceSheetLineNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oAuth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oAuth", ["Financials.ReadWrite.All"], configuration)

            if ($select) {
                localVarQueryParameter['$select'] = $select.join(COLLECTION_FORMATS.csv);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns a list of balanceSheet
         * @param {string} companyId (v1.0) id for company
         * @param {number} [$top] (v1.0) Number of items to return from the top of the list
         * @param {number} [$skip] (v1.0) Number of items to skip from the list
         * @param {number} [$limit] (v1.0) Number of items to return from the list
         * @param {string} [$filter] (v1.0) Filtering expression
         * @param {Array<ListBalanceSheetSelectEnum>} [$select] (v1.0) Selected properties to be retrieved
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBalanceSheet: async (companyId: string, $top?: number, $skip?: number, $limit?: number, $filter?: string, $select?: Array<ListBalanceSheetSelectEnum>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('listBalanceSheet', 'companyId', companyId)
            const localVarPath = `/companies({company_id})/balanceSheet`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oAuth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oAuth", ["Financials.ReadWrite.All"], configuration)

            if ($top !== undefined) {
                localVarQueryParameter['$top'] = $top;
            }

            if ($skip !== undefined) {
                localVarQueryParameter['$skip'] = $skip;
            }

            if ($limit !== undefined) {
                localVarQueryParameter['$limit'] = $limit;
            }

            if ($filter !== undefined) {
                localVarQueryParameter['$filter'] = $filter;
            }

            if ($select) {
                localVarQueryParameter['$select'] = $select.join(COLLECTION_FORMATS.csv);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BalanceSheetApi - functional programming interface
 * @export
 */
export const BalanceSheetApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BalanceSheetApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Retrieve the properties and relationships of an object of type balanceSheet for Dynamics 365 Business Central.
         * @param {string} companyId (v1.0) id for company
         * @param {number} balanceSheetLineNumber (v1.0) lineNumber for balanceSheet
         * @param {Array<GetBalanceSheetSelectEnum>} [$select] (v1.0) Selected properties to be retrieved
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBalanceSheet(companyId: string, balanceSheetLineNumber: number, $select?: Array<GetBalanceSheetSelectEnum>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BalanceSheet>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBalanceSheet(companyId, balanceSheetLineNumber, $select, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BalanceSheetApi.getBalanceSheet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Returns a list of balanceSheet
         * @param {string} companyId (v1.0) id for company
         * @param {number} [$top] (v1.0) Number of items to return from the top of the list
         * @param {number} [$skip] (v1.0) Number of items to skip from the list
         * @param {number} [$limit] (v1.0) Number of items to return from the list
         * @param {string} [$filter] (v1.0) Filtering expression
         * @param {Array<ListBalanceSheetSelectEnum>} [$select] (v1.0) Selected properties to be retrieved
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listBalanceSheet(companyId: string, $top?: number, $skip?: number, $limit?: number, $filter?: string, $select?: Array<ListBalanceSheetSelectEnum>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListBalanceSheet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listBalanceSheet(companyId, $top, $skip, $limit, $filter, $select, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BalanceSheetApi.listBalanceSheet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BalanceSheetApi - factory interface
 * @export
 */
export const BalanceSheetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BalanceSheetApiFp(configuration)
    return {
        /**
         * 
         * @summary Retrieve the properties and relationships of an object of type balanceSheet for Dynamics 365 Business Central.
         * @param {BalanceSheetApiGetBalanceSheetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBalanceSheet(requestParameters: BalanceSheetApiGetBalanceSheetRequest, options?: RawAxiosRequestConfig): AxiosPromise<BalanceSheet> {
            return localVarFp.getBalanceSheet(requestParameters.companyId, requestParameters.balanceSheetLineNumber, requestParameters.$select, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns a list of balanceSheet
         * @param {BalanceSheetApiListBalanceSheetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listBalanceSheet(requestParameters: BalanceSheetApiListBalanceSheetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListBalanceSheet200Response> {
            return localVarFp.listBalanceSheet(requestParameters.companyId, requestParameters.$top, requestParameters.$skip, requestParameters.$limit, requestParameters.$filter, requestParameters.$select, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getBalanceSheet operation in BalanceSheetApi.
 * @export
 * @interface BalanceSheetApiGetBalanceSheetRequest
 */
export interface BalanceSheetApiGetBalanceSheetRequest {
    /**
     * (v1.0) id for company
     * @type {string}
     * @memberof BalanceSheetApiGetBalanceSheet
     */
    readonly companyId: string

    /**
     * (v1.0) lineNumber for balanceSheet
     * @type {number}
     * @memberof BalanceSheetApiGetBalanceSheet
     */
    readonly balanceSheetLineNumber: number

    /**
     * (v1.0) Selected properties to be retrieved
     * @type {Array<'lineNumber' | 'display' | 'balance' | 'lineType' | 'indentation' | 'dateFilter'>}
     * @memberof BalanceSheetApiGetBalanceSheet
     */
    readonly $select?: Array<GetBalanceSheetSelectEnum>
}

/**
 * Request parameters for listBalanceSheet operation in BalanceSheetApi.
 * @export
 * @interface BalanceSheetApiListBalanceSheetRequest
 */
export interface BalanceSheetApiListBalanceSheetRequest {
    /**
     * (v1.0) id for company
     * @type {string}
     * @memberof BalanceSheetApiListBalanceSheet
     */
    readonly companyId: string

    /**
     * (v1.0) Number of items to return from the top of the list
     * @type {number}
     * @memberof BalanceSheetApiListBalanceSheet
     */
    readonly $top?: number

    /**
     * (v1.0) Number of items to skip from the list
     * @type {number}
     * @memberof BalanceSheetApiListBalanceSheet
     */
    readonly $skip?: number

    /**
     * (v1.0) Number of items to return from the list
     * @type {number}
     * @memberof BalanceSheetApiListBalanceSheet
     */
    readonly $limit?: number

    /**
     * (v1.0) Filtering expression
     * @type {string}
     * @memberof BalanceSheetApiListBalanceSheet
     */
    readonly $filter?: string

    /**
     * (v1.0) Selected properties to be retrieved
     * @type {Array<'lineNumber' | 'display' | 'balance' | 'lineType' | 'indentation' | 'dateFilter'>}
     * @memberof BalanceSheetApiListBalanceSheet
     */
    readonly $select?: Array<ListBalanceSheetSelectEnum>
}

/**
 * BalanceSheetApi - object-oriented interface
 * @export
 * @class BalanceSheetApi
 * @extends {BaseAPI}
 */
export class BalanceSheetApi extends BaseAPI {
    /**
     * 
     * @summary Retrieve the properties and relationships of an object of type balanceSheet for Dynamics 365 Business Central.
     * @param {BalanceSheetApiGetBalanceSheetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BalanceSheetApi
     */
    public getBalanceSheet(requestParameters: BalanceSheetApiGetBalanceSheetRequest, options?: RawAxiosRequestConfig) {
        return BalanceSheetApiFp(this.configuration).getBalanceSheet(requestParameters.companyId, requestParameters.balanceSheetLineNumber, requestParameters.$select, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns a list of balanceSheet
     * @param {BalanceSheetApiListBalanceSheetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BalanceSheetApi
     */
    public listBalanceSheet(requestParameters: BalanceSheetApiListBalanceSheetRequest, options?: RawAxiosRequestConfig) {
        return BalanceSheetApiFp(this.configuration).listBalanceSheet(requestParameters.companyId, requestParameters.$top, requestParameters.$skip, requestParameters.$limit, requestParameters.$filter, requestParameters.$select, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetBalanceSheetSelectEnum = {
    LineNumber: 'lineNumber',
    Display: 'display',
    Balance: 'balance',
    LineType: 'lineType',
    Indentation: 'indentation',
    DateFilter: 'dateFilter'
} as const;
export type GetBalanceSheetSelectEnum = typeof GetBalanceSheetSelectEnum[keyof typeof GetBalanceSheetSelectEnum];
/**
 * @export
 */
export const ListBalanceSheetSelectEnum = {
    LineNumber: 'lineNumber',
    Display: 'display',
    Balance: 'balance',
    LineType: 'lineType',
    Indentation: 'indentation',
    DateFilter: 'dateFilter'
} as const;
export type ListBalanceSheetSelectEnum = typeof ListBalanceSheetSelectEnum[keyof typeof ListBalanceSheetSelectEnum];
