/* tslint:disable */
/* eslint-disable */
/**
 * (v1.0) Dynamics 365 Business Central
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { IncomeStatement } from '../model';
// @ts-ignore
import type { ListIncomeStatement200Response } from '../model';
/**
 * IncomeStatementApi - axios parameter creator
 * @export
 */
export const IncomeStatementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Retrieve the properties and relationships of an object of type incomeStatement for Dynamics 365 Business Central.
         * @param {string} companyId (v1.0) id for company
         * @param {number} incomeStatementLineNumber (v1.0) lineNumber for incomeStatement
         * @param {Array<GetIncomeStatementSelectEnum>} [$select] (v1.0) Selected properties to be retrieved
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIncomeStatement: async (companyId: string, incomeStatementLineNumber: number, $select?: Array<GetIncomeStatementSelectEnum>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('getIncomeStatement', 'companyId', companyId)
            // verify required parameter 'incomeStatementLineNumber' is not null or undefined
            assertParamExists('getIncomeStatement', 'incomeStatementLineNumber', incomeStatementLineNumber)
            const localVarPath = `/companies({company_id})/incomeStatement({incomeStatement_lineNumber})`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)))
                .replace(`{${"incomeStatement_lineNumber"}}`, encodeURIComponent(String(incomeStatementLineNumber)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oAuth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oAuth", ["Financials.ReadWrite.All"], configuration)

            if ($select) {
                localVarQueryParameter['$select'] = $select.join(COLLECTION_FORMATS.csv);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns a list of incomeStatement
         * @param {string} companyId (v1.0) id for company
         * @param {number} [$top] (v1.0) Number of items to return from the top of the list
         * @param {number} [$skip] (v1.0) Number of items to skip from the list
         * @param {number} [$limit] (v1.0) Number of items to return from the list
         * @param {string} [$filter] (v1.0) Filtering expression
         * @param {Array<ListIncomeStatementSelectEnum>} [$select] (v1.0) Selected properties to be retrieved
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listIncomeStatement: async (companyId: string, $top?: number, $skip?: number, $limit?: number, $filter?: string, $select?: Array<ListIncomeStatementSelectEnum>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyId' is not null or undefined
            assertParamExists('listIncomeStatement', 'companyId', companyId)
            const localVarPath = `/companies({company_id})/incomeStatement`
                .replace(`{${"company_id"}}`, encodeURIComponent(String(companyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oAuth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "oAuth", ["Financials.ReadWrite.All"], configuration)

            if ($top !== undefined) {
                localVarQueryParameter['$top'] = $top;
            }

            if ($skip !== undefined) {
                localVarQueryParameter['$skip'] = $skip;
            }

            if ($limit !== undefined) {
                localVarQueryParameter['$limit'] = $limit;
            }

            if ($filter !== undefined) {
                localVarQueryParameter['$filter'] = $filter;
            }

            if ($select) {
                localVarQueryParameter['$select'] = $select.join(COLLECTION_FORMATS.csv);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IncomeStatementApi - functional programming interface
 * @export
 */
export const IncomeStatementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IncomeStatementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Retrieve the properties and relationships of an object of type incomeStatement for Dynamics 365 Business Central.
         * @param {string} companyId (v1.0) id for company
         * @param {number} incomeStatementLineNumber (v1.0) lineNumber for incomeStatement
         * @param {Array<GetIncomeStatementSelectEnum>} [$select] (v1.0) Selected properties to be retrieved
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIncomeStatement(companyId: string, incomeStatementLineNumber: number, $select?: Array<GetIncomeStatementSelectEnum>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IncomeStatement>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIncomeStatement(companyId, incomeStatementLineNumber, $select, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IncomeStatementApi.getIncomeStatement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Returns a list of incomeStatement
         * @param {string} companyId (v1.0) id for company
         * @param {number} [$top] (v1.0) Number of items to return from the top of the list
         * @param {number} [$skip] (v1.0) Number of items to skip from the list
         * @param {number} [$limit] (v1.0) Number of items to return from the list
         * @param {string} [$filter] (v1.0) Filtering expression
         * @param {Array<ListIncomeStatementSelectEnum>} [$select] (v1.0) Selected properties to be retrieved
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listIncomeStatement(companyId: string, $top?: number, $skip?: number, $limit?: number, $filter?: string, $select?: Array<ListIncomeStatementSelectEnum>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListIncomeStatement200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listIncomeStatement(companyId, $top, $skip, $limit, $filter, $select, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IncomeStatementApi.listIncomeStatement']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IncomeStatementApi - factory interface
 * @export
 */
export const IncomeStatementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IncomeStatementApiFp(configuration)
    return {
        /**
         * 
         * @summary Retrieve the properties and relationships of an object of type incomeStatement for Dynamics 365 Business Central.
         * @param {IncomeStatementApiGetIncomeStatementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIncomeStatement(requestParameters: IncomeStatementApiGetIncomeStatementRequest, options?: RawAxiosRequestConfig): AxiosPromise<IncomeStatement> {
            return localVarFp.getIncomeStatement(requestParameters.companyId, requestParameters.incomeStatementLineNumber, requestParameters.$select, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns a list of incomeStatement
         * @param {IncomeStatementApiListIncomeStatementRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listIncomeStatement(requestParameters: IncomeStatementApiListIncomeStatementRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListIncomeStatement200Response> {
            return localVarFp.listIncomeStatement(requestParameters.companyId, requestParameters.$top, requestParameters.$skip, requestParameters.$limit, requestParameters.$filter, requestParameters.$select, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getIncomeStatement operation in IncomeStatementApi.
 * @export
 * @interface IncomeStatementApiGetIncomeStatementRequest
 */
export interface IncomeStatementApiGetIncomeStatementRequest {
    /**
     * (v1.0) id for company
     * @type {string}
     * @memberof IncomeStatementApiGetIncomeStatement
     */
    readonly companyId: string

    /**
     * (v1.0) lineNumber for incomeStatement
     * @type {number}
     * @memberof IncomeStatementApiGetIncomeStatement
     */
    readonly incomeStatementLineNumber: number

    /**
     * (v1.0) Selected properties to be retrieved
     * @type {Array<'lineNumber' | 'display' | 'netChange' | 'lineType' | 'indentation' | 'dateFilter'>}
     * @memberof IncomeStatementApiGetIncomeStatement
     */
    readonly $select?: Array<GetIncomeStatementSelectEnum>
}

/**
 * Request parameters for listIncomeStatement operation in IncomeStatementApi.
 * @export
 * @interface IncomeStatementApiListIncomeStatementRequest
 */
export interface IncomeStatementApiListIncomeStatementRequest {
    /**
     * (v1.0) id for company
     * @type {string}
     * @memberof IncomeStatementApiListIncomeStatement
     */
    readonly companyId: string

    /**
     * (v1.0) Number of items to return from the top of the list
     * @type {number}
     * @memberof IncomeStatementApiListIncomeStatement
     */
    readonly $top?: number

    /**
     * (v1.0) Number of items to skip from the list
     * @type {number}
     * @memberof IncomeStatementApiListIncomeStatement
     */
    readonly $skip?: number

    /**
     * (v1.0) Number of items to return from the list
     * @type {number}
     * @memberof IncomeStatementApiListIncomeStatement
     */
    readonly $limit?: number

    /**
     * (v1.0) Filtering expression
     * @type {string}
     * @memberof IncomeStatementApiListIncomeStatement
     */
    readonly $filter?: string

    /**
     * (v1.0) Selected properties to be retrieved
     * @type {Array<'lineNumber' | 'display' | 'netChange' | 'lineType' | 'indentation' | 'dateFilter'>}
     * @memberof IncomeStatementApiListIncomeStatement
     */
    readonly $select?: Array<ListIncomeStatementSelectEnum>
}

/**
 * IncomeStatementApi - object-oriented interface
 * @export
 * @class IncomeStatementApi
 * @extends {BaseAPI}
 */
export class IncomeStatementApi extends BaseAPI {
    /**
     * 
     * @summary Retrieve the properties and relationships of an object of type incomeStatement for Dynamics 365 Business Central.
     * @param {IncomeStatementApiGetIncomeStatementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IncomeStatementApi
     */
    public getIncomeStatement(requestParameters: IncomeStatementApiGetIncomeStatementRequest, options?: RawAxiosRequestConfig) {
        return IncomeStatementApiFp(this.configuration).getIncomeStatement(requestParameters.companyId, requestParameters.incomeStatementLineNumber, requestParameters.$select, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns a list of incomeStatement
     * @param {IncomeStatementApiListIncomeStatementRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IncomeStatementApi
     */
    public listIncomeStatement(requestParameters: IncomeStatementApiListIncomeStatementRequest, options?: RawAxiosRequestConfig) {
        return IncomeStatementApiFp(this.configuration).listIncomeStatement(requestParameters.companyId, requestParameters.$top, requestParameters.$skip, requestParameters.$limit, requestParameters.$filter, requestParameters.$select, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetIncomeStatementSelectEnum = {
    LineNumber: 'lineNumber',
    Display: 'display',
    NetChange: 'netChange',
    LineType: 'lineType',
    Indentation: 'indentation',
    DateFilter: 'dateFilter'
} as const;
export type GetIncomeStatementSelectEnum = typeof GetIncomeStatementSelectEnum[keyof typeof GetIncomeStatementSelectEnum];
/**
 * @export
 */
export const ListIncomeStatementSelectEnum = {
    LineNumber: 'lineNumber',
    Display: 'display',
    NetChange: 'netChange',
    LineType: 'lineType',
    Indentation: 'indentation',
    DateFilter: 'dateFilter'
} as const;
export type ListIncomeStatementSelectEnum = typeof ListIncomeStatementSelectEnum[keyof typeof ListIncomeStatementSelectEnum];
